FROM ubuntu:latest
RUN apt-get update && apt-get -y install cron docker.io

ADD crontab /etc/cron.d/audit-cron
RUN chmod 0644 /etc/cron.d/audit-cron

CMD touch /var/log/cron.log && cron && tail -f /var/log/cron.log