cron:
  build: .
  dockerfile: Dockerfile-cron
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  links:
  - "app"

proxy:
  build: .
  dockerfile: Dockerfile-proxy
  ports:
  - "443:443"
  links:
  - "app"

app:
  build: .
  dockerfile: Dockerfile-app
  volumes:
  - ./app:/usr/src/app
  expose:
  - "3001"
  links:
  - "db"

db:
  image: couchbase:community-4.5.0
  volumes:
  - ./persistence:/opt/couchbase/var
  ports:
  - "8091:8091"
  - "8092:8092"
  - "8093:8093"
  - "11210:11210"
  - "11211:11211"